const bam = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6084",
          "21",
          "Touro"
        ],
        [
          "2º",
          "5462",
          "16",
          "Leão"
        ],
        [
          "3º",
          "5271",
          "18",
          "Porco"
        ],
        [
          "4º",
          "7249",
          "13",
          "Galo"
        ],
        [
          "5º",
          "1990",
          "23",
          "Urso"
        ],
        [
          "6º",
          "1101",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "8465",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "4875",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "9760",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "0481",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5091",
          "23",
          "Urso"
        ],
        [
          "2º",
          "9454",
          "14",
          "Gato"
        ],
        [
          "3º",
          "3980",
          "20",
          "Peru"
        ],
        [
          "4º",
          "5351",
          "13",
          "Galo"
        ],
        [
          "5º",
          "1934",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "8866",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "9600",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "2297",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "2830",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "2275",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0988",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "3695",
          "24",
          "Veado"
        ],
        [
          "3º",
          "6848",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "0511",
          "03",
          "Burro"
        ],
        [
          "5º",
          "5244",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "5252",
          "13",
          "Galo"
        ],
        [
          "7º",
          "9521",
          "06",
          "Cabra"
        ],
        [
          "8º",
          "2387",
          "22",
          "Tigre"
        ],
        [
          "9º",
          "4484",
          "21",
          "Touro"
        ],
        [
          "10º",
          "9705",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "19h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1254",
          "14",
          "Gato"
        ],
        [
          "2º",
          "3473",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "9137",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "9669",
          "18",
          "Porco"
        ],
        [
          "5º",
          "8401",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "0036",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "9549",
          "13",
          "Galo"
        ],
        [
          "8º",
          "2917",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "5222",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "0937",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "21h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1387",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "2884",
          "21",
          "Touro"
        ],
        [
          "3º",
          "3858",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "1145",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "3188",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "2793",
          "24",
          "Veado"
        ],
        [
          "7º",
          "3191",
          "23",
          "Urso"
        ],
        [
          "8º",
          "2794",
          "24",
          "Veado"
        ],
        [
          "9º",
          "2665",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "5943",
          "11",
          "Cavalo"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7556",
          "14",
          "Gato"
        ],
        [
          "2º",
          "2240",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "4768",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "9124",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "0991",
          "23",
          "Urso"
        ],
        [
          "6º",
          "9481",
          "21",
          "Touro"
        ],
        [
          "7º",
          "7841",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "6760",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "0551",
          "13",
          "Galo"
        ],
        [
          "10º",
          "1840",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5395",
          "24",
          "Veado"
        ],
        [
          "2º",
          "3940",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "5859",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "1041",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4391",
          "23",
          "Urso"
        ],
        [
          "6º",
          "2298",
          "25",
          "Vaca"
        ],
        [
          "7º",
          "8268",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "3906",
          "02",
          "Águia"
        ],
        [
          "9º",
          "0706",
          "02",
          "Águia"
        ],
        [
          "10º",
          "5722",
          "06",
          "Cabra"
        ]
      ]
    },
    {
      "titulo": "15h - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0630",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "5869",
          "18",
          "Porco"
        ],
        [
          "3º",
          "1498",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "1858",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "4425",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "4295",
          "24",
          "Veado"
        ],
        [
          "7º",
          "4352",
          "13",
          "Galo"
        ],
        [
          "8º",
          "8825",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "4712",
          "03",
          "Burro"
        ],
        [
          "10º",
          "5079",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "19h - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9931",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "6142",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "6375",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "9734",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "1048",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "5290",
          "23",
          "Urso"
        ],
        [
          "7º",
          "2950",
          "13",
          "Galo"
        ],
        [
          "8º",
          "2143",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "2796",
          "24",
          "Veado"
        ],
        [
          "10º",
          "7390",
          "23",
          "Urso"
        ]
      ]
    },
    {
      "titulo": "21h - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1321",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "1883",
          "21",
          "Touro"
        ],
        [
          "3º",
          "4588",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "5847",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "8813",
          "04",
          "Borboleta"
        ],
        [
          "6º",
          "2232",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "6717",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "6999",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "5413",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "3495",
          "24",
          "Veado"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3258",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "8434",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "0983",
          "21",
          "Touro"
        ],
        [
          "4º",
          "3261",
          "16",
          "Leão"
        ],
        [
          "5º",
          "4038",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "2021",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "0793",
          "24",
          "Veado"
        ],
        [
          "8º",
          "3600",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "2466",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "0165",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0324",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "2392",
          "23",
          "Urso"
        ],
        [
          "3º",
          "2947",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "6416",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "8429",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "8589",
          "23",
          "Urso"
        ],
        [
          "7º",
          "8035",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "1989",
          "23",
          "Urso"
        ],
        [
          "9º",
          "3821",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "2448",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 15:45 (tarde II)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0536",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "2391",
          "23",
          "Urso"
        ],
        [
          "3º",
          "3598",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "4682",
          "21",
          "Touro"
        ],
        [
          "5º",
          "6144",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "6604",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "4758",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "3416",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "1028",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "8189",
          "23",
          "Urso"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 19:00 (noite)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7681",
          "21",
          "Touro"
        ],
        [
          "2º",
          "0096",
          "24",
          "Veado"
        ],
        [
          "3º",
          "2476",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "2565",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "5037",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "0712",
          "03",
          "Burro"
        ],
        [
          "7º",
          "8938",
          "10",
          "Coelho"
        ],
        [
          "8º",
          "4798",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "6890",
          "23",
          "Urso"
        ],
        [
          "10º",
          "9052",
          "13",
          "Galo"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2294",
          "24",
          "Veado"
        ],
        [
          "2º",
          "5388",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "1735",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "6524",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "7299",
          "25",
          "Vaca"
        ],
        [
          "6º [soma]",
          "3240",
          "",
          ""
        ],
        [
          "7º [mult]",
          "360",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2294",
          "24",
          "Veado"
        ],
        [
          "2º",
          "5388",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "1735",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "6524",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "7299",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "2516",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "2375",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "9832",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "4854",
          "14",
          "Gato"
        ],
        [
          "10º",
          "2817",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2353",
          "14",
          "Gato"
        ],
        [
          "2º",
          "2048",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "7725",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "4264",
          "16",
          "Leão"
        ],
        [
          "5º",
          "6460",
          "15",
          "Jacaré"
        ],
        [
          "6º [soma]",
          "2850",
          "",
          ""
        ],
        [
          "7º [mult]",
          "818",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2353",
          "14",
          "Gato"
        ],
        [
          "2º",
          "2048",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "7725",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "4264",
          "16",
          "Leão"
        ],
        [
          "5º",
          "6460",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "2274",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "3072",
          "18",
          "Porco"
        ],
        [
          "8º",
          "5426",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "3854",
          "14",
          "Gato"
        ],
        [
          "10º",
          "7476",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8756",
          "14",
          "Gato"
        ],
        [
          "2º",
          "1717",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "0980",
          "20",
          "Peru"
        ],
        [
          "4º",
          "9940",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "4946",
          "12",
          "Elefante"
        ],
        [
          "6º [soma]",
          "6339",
          "",
          ""
        ],
        [
          "7º [mult]",
          "034",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8756",
          "14",
          "Gato"
        ],
        [
          "2º",
          "1717",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "0980",
          "20",
          "Peru"
        ],
        [
          "4º",
          "9940",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "4946",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "8109",
          "03",
          "Burro"
        ],
        [
          "7º",
          "7799",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "5184",
          "21",
          "Touro"
        ],
        [
          "9º",
          "6700",
          "25",
          "Vaca"
        ],
        [
          "10º",
          "4131",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1981",
          "21",
          "Touro"
        ],
        [
          "2º",
          "4038",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "9006",
          "02",
          "Águia"
        ],
        [
          "4º",
          "2207",
          "02",
          "Águia"
        ],
        [
          "5º",
          "9406",
          "02",
          "Águia"
        ],
        [
          "6º [soma]",
          "6638",
          "",
          ""
        ],
        [
          "7º [mult]",
          "999",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1981",
          "21",
          "Touro"
        ],
        [
          "2º",
          "4038",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "9006",
          "02",
          "Águia"
        ],
        [
          "4º",
          "2207",
          "02",
          "Águia"
        ],
        [
          "5º",
          "9406",
          "02",
          "Águia"
        ],
        [
          "6º",
          "1492",
          "23",
          "Urso"
        ],
        [
          "7º",
          "9002",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "8300",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "1867",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "7299",
          "25",
          "Vaca"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6829",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "0855",
          "14",
          "Gato"
        ],
        [
          "3º",
          "3297",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "9103",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "3975",
          "19",
          "Pavão"
        ],
        [
          "6º [soma]",
          "4059",
          "",
          ""
        ],
        [
          "7º [mult]",
          "838",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6829",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "0855",
          "14",
          "Gato"
        ],
        [
          "3º",
          "3297",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "9103",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "3975",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "6039",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "8821",
          "06",
          "Cabra"
        ],
        [
          "8º",
          "2590",
          "23",
          "Urso"
        ],
        [
          "9º",
          "9573",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "1082",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9675",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "9197",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "3248",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "8563",
          "16",
          "Leão"
        ],
        [
          "5º",
          "6687",
          "22",
          "Tigre"
        ],
        [
          "6º [soma]",
          "7370",
          "",
          ""
        ],
        [
          "7º [mult]",
          "980",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9675",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "9197",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "3248",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "8563",
          "16",
          "Leão"
        ],
        [
          "5º",
          "6687",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "9938",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "6125",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "7946",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "5783",
          "21",
          "Touro"
        ],
        [
          "10º",
          "7162",
          "16",
          "Leão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 21h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1108",
          "02",
          "Águia"
        ],
        [
          "2º",
          "8596",
          "24",
          "Veado"
        ],
        [
          "3º",
          "1852",
          "13",
          "Galo"
        ],
        [
          "4º",
          "6555",
          "14",
          "Gato"
        ],
        [
          "5º",
          "3199",
          "25",
          "Vaca"
        ],
        [
          "6º [soma]",
          "1310",
          "",
          ""
        ],
        [
          "7º [mult]",
          "524",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 21h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1108",
          "02",
          "Águia"
        ],
        [
          "2º",
          "8596",
          "24",
          "Veado"
        ],
        [
          "3º",
          "1852",
          "13",
          "Galo"
        ],
        [
          "4º",
          "6555",
          "14",
          "Gato"
        ],
        [
          "5º",
          "3199",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "1816",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "1585",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "0955",
          "14",
          "Gato"
        ],
        [
          "9º",
          "8625",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "4291",
          "23",
          "Urso"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1183",
          "21",
          "Touro"
        ],
        [
          "2º",
          "8808",
          "02",
          "Águia"
        ],
        [
          "3º",
          "8222",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "5842",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "0806",
          "02",
          "Águia"
        ],
        [
          "6º",
          "1885",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "1828",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "8024",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "3822",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "0420",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0581",
          "21",
          "Touro"
        ],
        [
          "2º",
          "6044",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "7694",
          "24",
          "Veado"
        ],
        [
          "4º",
          "8024",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "0895",
          "24",
          "Veado"
        ],
        [
          "6º",
          "0678",
          "20",
          "Peru"
        ],
        [
          "7º",
          "5060",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "8492",
          "23",
          "Urso"
        ],
        [
          "9º",
          "1444",
          "11",
          "Cavalo"
        ],
        [
          "10º",
          "8912",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5412",
          "03",
          "Burro"
        ],
        [
          "2º",
          "6894",
          "24",
          "Veado"
        ],
        [
          "3º",
          "3703",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "1452",
          "13",
          "Galo"
        ],
        [
          "5º",
          "7173",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "5631",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "4874",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "1905",
          "02",
          "Águia"
        ],
        [
          "9º",
          "2432",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "9476",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 15:45h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7625",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "8720",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "9657",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "0888",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "6792",
          "23",
          "Urso"
        ],
        [
          "6º",
          "7890",
          "23",
          "Urso"
        ],
        [
          "7º",
          "6768",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "2258",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "5078",
          "20",
          "Peru"
        ],
        [
          "10º",
          "5676",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 18h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0427",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "8744",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "0472",
          "18",
          "Porco"
        ],
        [
          "4º",
          "7529",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "2778",
          "20",
          "Peru"
        ],
        [
          "6º",
          "0807",
          "02",
          "Águia"
        ],
        [
          "7º",
          "4745",
          "12",
          "Elefante"
        ],
        [
          "8º",
          "2472",
          "18",
          "Porco"
        ],
        [
          "9º",
          "7429",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "5403",
          "01",
          "Avestruz"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 20:00",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2520",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "4057",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "8595",
          "24",
          "Veado"
        ],
        [
          "4º",
          "0565",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "5735",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "2480",
          "20",
          "Peru"
        ],
        [
          "7º",
          "5055",
          "14",
          "Gato"
        ],
        [
          "8º",
          "2596",
          "24",
          "Veado"
        ],
        [
          "9º",
          "0755",
          "14",
          "Gato"
        ],
        [
          "10º",
          "2358",
          "15",
          "Jacaré"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3269",
          "18",
          "Porco"
        ],
        [
          "2º",
          "5745",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "2738",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "3832",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "3163",
          "16",
          "Leão"
        ],
        [
          "6º [soma]",
          "8747",
          "",
          ""
        ],
        [
          "7º [mult]",
          "780",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3269",
          "18",
          "Porco"
        ],
        [
          "2º",
          "5745",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "2738",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "3832",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "3163",
          "16",
          "Leão"
        ],
        [
          "6º",
          "3523",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "2778",
          "20",
          "Peru"
        ],
        [
          "8º",
          "6433",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "9582",
          "21",
          "Touro"
        ],
        [
          "10º",
          "1063",
          "16",
          "Leão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3530",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "5528",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "3376",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "0949",
          "13",
          "Galo"
        ],
        [
          "5º",
          "6032",
          "08",
          "Camelo"
        ],
        [
          "6º [soma]",
          "9415",
          "",
          ""
        ],
        [
          "7º [mult]",
          "513",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3530",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "5528",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "3376",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "0949",
          "13",
          "Galo"
        ],
        [
          "5º",
          "6032",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "3530",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "5539",
          "10",
          "Coelho"
        ],
        [
          "8º",
          "3274",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "0869",
          "18",
          "Porco"
        ],
        [
          "10º",
          "2627",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6817",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "1655",
          "14",
          "Gato"
        ],
        [
          "3º",
          "4666",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "3736",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "4438",
          "10",
          "Coelho"
        ],
        [
          "6º [soma]",
          "1312",
          "",
          ""
        ],
        [
          "7º [mult]",
          "282",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6817",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "1655",
          "14",
          "Gato"
        ],
        [
          "3º",
          "4666",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "3736",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "4438",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "6143",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "8667",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "1563",
          "16",
          "Leão"
        ],
        [
          "9º",
          "7566",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "5251",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4425",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "3550",
          "13",
          "Galo"
        ],
        [
          "3º",
          "5809",
          "03",
          "Burro"
        ],
        [
          "4º",
          "0383",
          "21",
          "Touro"
        ],
        [
          "5º",
          "4051",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "8218",
          "",
          ""
        ],
        [
          "7º [mult]",
          "708",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4425",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "3550",
          "13",
          "Galo"
        ],
        [
          "3º",
          "5809",
          "03",
          "Burro"
        ],
        [
          "4º",
          "0383",
          "21",
          "Touro"
        ],
        [
          "5º",
          "4051",
          "13",
          "Galo"
        ],
        [
          "6º",
          "4350",
          "13",
          "Galo"
        ],
        [
          "7º",
          "4583",
          "21",
          "Touro"
        ],
        [
          "8º",
          "2508",
          "02",
          "Águia"
        ],
        [
          "9º",
          "5093",
          "24",
          "Veado"
        ],
        [
          "10º",
          "4752",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2664",
          "16",
          "Leão"
        ],
        [
          "2º",
          "3303",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "7996",
          "24",
          "Veado"
        ],
        [
          "4º",
          "2894",
          "24",
          "Veado"
        ],
        [
          "5º",
          "1949",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "8806",
          "",
          ""
        ],
        [
          "7º [mult]",
          "799",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2664",
          "16",
          "Leão"
        ],
        [
          "2º",
          "3303",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "7996",
          "24",
          "Veado"
        ],
        [
          "4º",
          "2894",
          "24",
          "Veado"
        ],
        [
          "5º",
          "1949",
          "13",
          "Galo"
        ],
        [
          "6º",
          "2372",
          "18",
          "Porco"
        ],
        [
          "7º",
          "6398",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "6099",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "4364",
          "16",
          "Leão"
        ],
        [
          "10º",
          "8039",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 21:20, CORUJA, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3317",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "1990",
          "23",
          "Urso"
        ],
        [
          "3º",
          "4993",
          "24",
          "Veado"
        ],
        [
          "4º",
          "6189",
          "23",
          "Urso"
        ],
        [
          "5º",
          "9713",
          "04",
          "Borboleta"
        ],
        [
          "6º [soma]",
          "6202",
          "",
          ""
        ],
        [
          "7º [mult]",
          "600",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 21:20, CORUJA, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3317",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "1990",
          "23",
          "Urso"
        ],
        [
          "3º",
          "4993",
          "24",
          "Veado"
        ],
        [
          "4º",
          "6189",
          "23",
          "Urso"
        ],
        [
          "5º",
          "9713",
          "04",
          "Borboleta"
        ],
        [
          "6º",
          "3146",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "3991",
          "23",
          "Urso"
        ],
        [
          "8º",
          "1998",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "7039",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "2376",
          "19",
          "Pavão"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3103",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "3508",
          "02",
          "Águia"
        ],
        [
          "3º",
          "7496",
          "24",
          "Veado"
        ],
        [
          "4º",
          "1461",
          "16",
          "Leão"
        ],
        [
          "5º",
          "8996",
          "24",
          "Veado"
        ],
        [
          "6º [soma]",
          "4564",
          "",
          ""
        ],
        [
          "7º [mult]",
          "885",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3103",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "3508",
          "02",
          "Águia"
        ],
        [
          "3º",
          "7496",
          "24",
          "Veado"
        ],
        [
          "4º",
          "1461",
          "16",
          "Leão"
        ],
        [
          "5º",
          "8996",
          "24",
          "Veado"
        ],
        [
          "6º",
          "3371",
          "18",
          "Porco"
        ],
        [
          "7º",
          "1544",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "0096",
          "24",
          "Veado"
        ],
        [
          "9º",
          "3861",
          "16",
          "Leão"
        ],
        [
          "10º",
          "3436",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5602",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "3758",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "2691",
          "23",
          "Urso"
        ],
        [
          "4º",
          "1749",
          "13",
          "Galo"
        ],
        [
          "5º",
          "2887",
          "22",
          "Tigre"
        ],
        [
          "6º [soma]",
          "6687",
          "",
          ""
        ],
        [
          "7º [mult]",
          "052",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5602",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "3758",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "2691",
          "23",
          "Urso"
        ],
        [
          "4º",
          "1749",
          "13",
          "Galo"
        ],
        [
          "5º",
          "2887",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "5321",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "6767",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "0594",
          "24",
          "Veado"
        ],
        [
          "9º",
          "2819",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "2188",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6678",
          "20",
          "Peru"
        ],
        [
          "2º",
          "9642",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "0771",
          "18",
          "Porco"
        ],
        [
          "4º",
          "1917",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "3396",
          "24",
          "Veado"
        ],
        [
          "6º [soma]",
          "2404",
          "",
          ""
        ],
        [
          "7º [mult]",
          "389",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6678",
          "20",
          "Peru"
        ],
        [
          "2º",
          "9642",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "0771",
          "18",
          "Porco"
        ],
        [
          "4º",
          "1917",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "3396",
          "24",
          "Veado"
        ],
        [
          "6º",
          "6901",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "6679",
          "20",
          "Peru"
        ],
        [
          "8º",
          "7471",
          "18",
          "Porco"
        ],
        [
          "9º",
          "8217",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "1672",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4737",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "6121",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "8033",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "5070",
          "18",
          "Porco"
        ],
        [
          "5º",
          "7721",
          "06",
          "Cabra"
        ],
        [
          "6º [soma]",
          "1682",
          "",
          ""
        ],
        [
          "7º [mult]",
          "995",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4737",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "6121",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "8033",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "5070",
          "18",
          "Porco"
        ],
        [
          "5º",
          "7721",
          "06",
          "Cabra"
        ],
        [
          "6º",
          "4685",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "7100",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "3237",
          "10",
          "Coelho"
        ],
        [
          "9º",
          "7130",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "3834",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0826",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "7250",
          "13",
          "Galo"
        ],
        [
          "3º",
          "7323",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "3194",
          "24",
          "Veado"
        ],
        [
          "5º",
          "0291",
          "23",
          "Urso"
        ],
        [
          "6º [soma]",
          "8884",
          "",
          ""
        ],
        [
          "7º [mult]",
          "988",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0826",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "7250",
          "13",
          "Galo"
        ],
        [
          "3º",
          "7323",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "3194",
          "24",
          "Veado"
        ],
        [
          "5º",
          "0291",
          "23",
          "Urso"
        ],
        [
          "6º",
          "0773",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "8231",
          "08",
          "Camelo"
        ],
        [
          "8º",
          "2529",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "6034",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "6451",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6246",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "7898",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "1667",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "5654",
          "14",
          "Gato"
        ],
        [
          "5º",
          "1229",
          "08",
          "Camelo"
        ],
        [
          "6º [soma]",
          "2694",
          "",
          ""
        ],
        [
          "7º [mult]",
          "330",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6246",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "7898",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "1667",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "5654",
          "14",
          "Gato"
        ],
        [
          "5º",
          "1229",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "6715",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "2866",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "4965",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "6874",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "4114",
          "04",
          "Borboleta"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4319",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "5519",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "6595",
          "24",
          "Veado"
        ],
        [
          "4º",
          "6925",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "2051",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "5409",
          "",
          ""
        ],
        [
          "7º [mult]",
          "836",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4319",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "5519",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "6595",
          "24",
          "Veado"
        ],
        [
          "4º",
          "6925",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "2051",
          "13",
          "Galo"
        ],
        [
          "6º",
          "4566",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "3559",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "1192",
          "23",
          "Urso"
        ],
        [
          "9º",
          "9955",
          "14",
          "Gato"
        ],
        [
          "10º",
          "4681",
          "21",
          "Touro"
        ]
      ]
    }
  ],
  "NACIONAL": [
    {
      "titulo": "Nacional - LN 02:00 - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5639",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "5721",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "5725",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "5126",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "9520",
          "05",
          "Cachorro"
        ],
        [
          "6º [soma]",
          "1731",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 08:00 - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8367",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "5069",
          "18",
          "Porco"
        ],
        [
          "3º",
          "9477",
          "20",
          "Peru"
        ],
        [
          "4º",
          "7630",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "3839",
          "10",
          "Coelho"
        ],
        [
          "6º [soma]",
          "4382",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 10:00 - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8786",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "9951",
          "13",
          "Galo"
        ],
        [
          "3º",
          "9477",
          "20",
          "Peru"
        ],
        [
          "4º",
          "9990",
          "23",
          "Urso"
        ],
        [
          "5º",
          "2611",
          "03",
          "Burro"
        ],
        [
          "6º [soma]",
          "0815",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 12:00 - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0472",
          "18",
          "Porco"
        ],
        [
          "2º",
          "9458",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "6617",
          "05",
          "Cachorro"
        ],
        [
          "4º",
          "5329",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "8173",
          "19",
          "Pavão"
        ],
        [
          "6º [soma]",
          "0049",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 15:00 - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6652",
          "13",
          "Galo"
        ],
        [
          "2º",
          "6763",
          "16",
          "Leão"
        ],
        [
          "3º",
          "6009",
          "03",
          "Burro"
        ],
        [
          "4º",
          "5468",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "1980",
          "20",
          "Peru"
        ],
        [
          "6º [soma]",
          "6872",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 17:00 - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1554",
          "14",
          "Gato"
        ],
        [
          "2º",
          "3680",
          "20",
          "Peru"
        ],
        [
          "3º",
          "1124",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "2957",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "1477",
          "20",
          "Peru"
        ],
        [
          "6º [soma]",
          "0792",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 20:00 - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7702",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "9152",
          "13",
          "Galo"
        ],
        [
          "3º",
          "3691",
          "23",
          "Urso"
        ],
        [
          "4º",
          "4874",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "6927",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "2346",
          "",
          ""
        ]
      ]
    }
  ]
};