const resultado = {
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2341",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "5621",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "9913",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "6513",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "3812",
          "03",
          "Burro"
        ],
        [
          "6º [soma]",
          "8200",
          "",
          ""
        ],
        [
          "7º [mult]",
          "158",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2341",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "5621",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "9913",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "6513",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "3812",
          "03",
          "Burro"
        ],
        [
          "6º",
          "2596",
          "24",
          "Veado"
        ],
        [
          "7º",
          "3695",
          "24",
          "Veado"
        ],
        [
          "8º",
          "4211",
          "03",
          "Burro"
        ],
        [
          "9º",
          "1133",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "9835",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5948",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "8639",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "7036",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "4405",
          "02",
          "Águia"
        ],
        [
          "5º",
          "8321",
          "06",
          "Cabra"
        ],
        [
          "6º [soma]",
          "4349",
          "",
          ""
        ],
        [
          "7º [mult]",
          "384",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5948",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "8639",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "7036",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "4405",
          "02",
          "Águia"
        ],
        [
          "5º",
          "8321",
          "06",
          "Cabra"
        ],
        [
          "6º",
          "5874",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "9604",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "4330",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "8965",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "3122",
          "06",
          "Cabra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6534",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "5862",
          "16",
          "Leão"
        ],
        [
          "3º",
          "5610",
          "03",
          "Burro"
        ],
        [
          "4º",
          "3843",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "3516",
          "04",
          "Borboleta"
        ],
        [
          "6º [soma]",
          "5365",
          "",
          ""
        ],
        [
          "7º [mult]",
          "302",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6534",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "5862",
          "16",
          "Leão"
        ],
        [
          "3º",
          "5610",
          "03",
          "Burro"
        ],
        [
          "4º",
          "3843",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "3516",
          "04",
          "Borboleta"
        ],
        [
          "6º",
          "6553",
          "14",
          "Gato"
        ],
        [
          "7º",
          "5868",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "3614",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "4203",
          "01",
          "Avestruz"
        ],
        [
          "10º",
          "5603",
          "01",
          "Avestruz"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4546",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "3520",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "0428",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "3237",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "5047",
          "12",
          "Elefante"
        ],
        [
          "6º [soma]",
          "6778",
          "",
          ""
        ],
        [
          "7º [mult]",
          "001",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4546",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "3520",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "0428",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "3237",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "5047",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "4303",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "5542",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "4223",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "6087",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "6933",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1896",
          "24",
          "Veado"
        ],
        [
          "2º",
          "4639",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "2527",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "8257",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "3816",
          "04",
          "Borboleta"
        ],
        [
          "6º [soma]",
          "1135",
          "",
          ""
        ],
        [
          "7º [mult]",
          "795",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1896",
          "24",
          "Veado"
        ],
        [
          "2º",
          "4639",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "2527",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "8257",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "3816",
          "04",
          "Borboleta"
        ],
        [
          "6º",
          "1428",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "8652",
          "13",
          "Galo"
        ],
        [
          "8º",
          "9325",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "6977",
          "20",
          "Peru"
        ],
        [
          "10º",
          "7517",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 21:20, CORUJA, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2276",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "8589",
          "23",
          "Urso"
        ],
        [
          "3º",
          "1475",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "6098",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "3027",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "1465",
          "",
          ""
        ],
        [
          "7º [mult]",
          "548",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 21:20, CORUJA, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2276",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "8589",
          "23",
          "Urso"
        ],
        [
          "3º",
          "1475",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "6098",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "3027",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "2816",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "2540",
          "10",
          "Coelho"
        ],
        [
          "8º",
          "7879",
          "20",
          "Peru"
        ],
        [
          "9º",
          "6958",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "1658",
          "15",
          "Jacaré"
        ]
      ]
    }
  ]
};