const bam = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2540",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "8688",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "0088",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "3154",
          "14",
          "Gato"
        ],
        [
          "5º",
          "9250",
          "13",
          "Galo"
        ],
        [
          "6º",
          "8548",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "8059",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "7642",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "7516",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "8242",
          "11",
          "Cavalo"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0370",
          "18",
          "Porco"
        ],
        [
          "2º",
          "6018",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "2959",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "5993",
          "24",
          "Veado"
        ],
        [
          "5º",
          "2551",
          "13",
          "Galo"
        ],
        [
          "6º",
          "3816",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "5822",
          "06",
          "Cabra"
        ],
        [
          "8º",
          "4456",
          "14",
          "Gato"
        ],
        [
          "9º",
          "4959",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "7047",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6012",
          "03",
          "Burro"
        ],
        [
          "2º",
          "6591",
          "23",
          "Urso"
        ],
        [
          "3º",
          "5930",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "0557",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "7396",
          "24",
          "Veado"
        ],
        [
          "6º",
          "5695",
          "24",
          "Veado"
        ],
        [
          "7º",
          "0291",
          "23",
          "Urso"
        ],
        [
          "8º",
          "6474",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "5051",
          "13",
          "Galo"
        ],
        [
          "10º",
          "2687",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "19h - MALUCA - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7285",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "4669",
          "18",
          "Porco"
        ],
        [
          "3º",
          "5213",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "5979",
          "20",
          "Peru"
        ],
        [
          "5º",
          "7528",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "1546",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "8584",
          "21",
          "Touro"
        ],
        [
          "8º",
          "6119",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "3271",
          "18",
          "Porco"
        ],
        [
          "10º",
          "1342",
          "11",
          "Cavalo"
        ]
      ]
    },
    {
      "titulo": "21h - MALUCA - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0309",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2162",
          "16",
          "Leão"
        ],
        [
          "3º",
          "3210",
          "03",
          "Burro"
        ],
        [
          "4º",
          "6811",
          "03",
          "Burro"
        ],
        [
          "5º",
          "6309",
          "03",
          "Burro"
        ],
        [
          "6º",
          "5278",
          "20",
          "Peru"
        ],
        [
          "7º",
          "2631",
          "08",
          "Camelo"
        ],
        [
          "8º",
          "1725",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "5881",
          "21",
          "Touro"
        ],
        [
          "10º",
          "9208",
          "02",
          "Águia"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3082",
          "21",
          "Touro"
        ],
        [
          "2º",
          "1065",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "5884",
          "21",
          "Touro"
        ],
        [
          "4º",
          "4880",
          "20",
          "Peru"
        ],
        [
          "5º",
          "0529",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "7788",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "5605",
          "02",
          "Águia"
        ],
        [
          "8º",
          "1454",
          "14",
          "Gato"
        ],
        [
          "9º",
          "6298",
          "25",
          "Vaca"
        ],
        [
          "10º",
          "2428",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5260",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "9903",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "9517",
          "05",
          "Cachorro"
        ],
        [
          "4º",
          "3980",
          "20",
          "Peru"
        ],
        [
          "5º",
          "1552",
          "13",
          "Galo"
        ],
        [
          "6º",
          "4453",
          "14",
          "Gato"
        ],
        [
          "7º",
          "9488",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "5521",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "9626",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "7407",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "15h - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0566",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "5950",
          "13",
          "Galo"
        ],
        [
          "3º",
          "5391",
          "23",
          "Urso"
        ],
        [
          "4º",
          "7012",
          "03",
          "Burro"
        ],
        [
          "5º",
          "6937",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "5605",
          "02",
          "Águia"
        ],
        [
          "7º",
          "0426",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "5799",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "1415",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "7862",
          "16",
          "Leão"
        ]
      ]
    },
    {
      "titulo": "19h - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5547",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "9262",
          "16",
          "Leão"
        ],
        [
          "3º",
          "7168",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "9395",
          "24",
          "Veado"
        ],
        [
          "5º",
          "8257",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "3681",
          "21",
          "Touro"
        ],
        [
          "7º",
          "2155",
          "14",
          "Gato"
        ],
        [
          "8º",
          "7184",
          "21",
          "Touro"
        ],
        [
          "9º",
          "1946",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "2431",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "21h - BA - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6320",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "8213",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "1160",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "1029",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "9036",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "5125",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "8762",
          "16",
          "Leão"
        ],
        [
          "8º",
          "8237",
          "10",
          "Coelho"
        ],
        [
          "9º",
          "1518",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "8029",
          "08",
          "Camelo"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1456",
          "14",
          "Gato"
        ],
        [
          "2º",
          "9798",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "8701",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "2541",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "1598",
          "25",
          "Vaca"
        ],
        [
          "6º [soma]",
          "4094",
          "",
          ""
        ],
        [
          "7º [mult]",
          "265",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1456",
          "14",
          "Gato"
        ],
        [
          "2º",
          "9798",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "8701",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "2541",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "1598",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "1982",
          "21",
          "Touro"
        ],
        [
          "7º",
          "4775",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "5904",
          "01",
          "Avestruz"
        ],
        [
          "9º",
          "6811",
          "03",
          "Burro"
        ],
        [
          "10º",
          "3566",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4463",
          "16",
          "Leão"
        ],
        [
          "2º",
          "9539",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "5701",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "8084",
          "21",
          "Touro"
        ],
        [
          "5º",
          "0509",
          "03",
          "Burro"
        ],
        [
          "6º [soma]",
          "8296",
          "",
          ""
        ],
        [
          "7º [mult]",
          "572",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4463",
          "16",
          "Leão"
        ],
        [
          "2º",
          "9539",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "5701",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "8084",
          "21",
          "Touro"
        ],
        [
          "5º",
          "0509",
          "03",
          "Burro"
        ],
        [
          "6º",
          "4958",
          "15",
          "Jacaré"
        ],
        [
          "7º",
          "4570",
          "18",
          "Porco"
        ],
        [
          "8º",
          "6308",
          "02",
          "Águia"
        ],
        [
          "9º",
          "3914",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "8046",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8805",
          "02",
          "Águia"
        ],
        [
          "2º",
          "8758",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "1170",
          "18",
          "Porco"
        ],
        [
          "4º",
          "3391",
          "23",
          "Urso"
        ],
        [
          "5º",
          "3551",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "5675",
          "",
          ""
        ],
        [
          "7º [mult]",
          "114",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8805",
          "02",
          "Águia"
        ],
        [
          "2º",
          "8758",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "1170",
          "18",
          "Porco"
        ],
        [
          "4º",
          "3391",
          "23",
          "Urso"
        ],
        [
          "5º",
          "3551",
          "13",
          "Galo"
        ],
        [
          "6º",
          "8813",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "8713",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "0579",
          "20",
          "Peru"
        ],
        [
          "9º",
          "5801",
          "01",
          "Avestruz"
        ],
        [
          "10º",
          "9581",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7441",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "4053",
          "14",
          "Gato"
        ],
        [
          "3º",
          "2085",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "1704",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "6050",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "1333",
          "",
          ""
        ],
        [
          "7º [mult]",
          "158",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7441",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "4053",
          "14",
          "Gato"
        ],
        [
          "3º",
          "2085",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "1704",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "6050",
          "13",
          "Galo"
        ],
        [
          "6º",
          "7421",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "4007",
          "02",
          "Águia"
        ],
        [
          "8º",
          "4580",
          "20",
          "Peru"
        ],
        [
          "9º",
          "1354",
          "14",
          "Gato"
        ],
        [
          "10º",
          "8695",
          "24",
          "Veado"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2399",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "6415",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "4101",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "4020",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "2129",
          "08",
          "Camelo"
        ],
        [
          "6º [soma]",
          "9064",
          "",
          ""
        ],
        [
          "7º [mult]",
          "389",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2399",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "6415",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "4101",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "4020",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "2129",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "2644",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "3410",
          "03",
          "Burro"
        ],
        [
          "8º",
          "9102",
          "01",
          "Avestruz"
        ],
        [
          "9º",
          "9510",
          "03",
          "Burro"
        ],
        [
          "10º",
          "3730",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1729",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "9508",
          "02",
          "Águia"
        ],
        [
          "3º",
          "6151",
          "13",
          "Galo"
        ],
        [
          "4º",
          "2666",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "3047",
          "12",
          "Elefante"
        ],
        [
          "6º [soma]",
          "3101",
          "",
          ""
        ],
        [
          "7º [mult]",
          "439",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1729",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "9508",
          "02",
          "Águia"
        ],
        [
          "3º",
          "6151",
          "13",
          "Galo"
        ],
        [
          "4º",
          "2666",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "3047",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "1962",
          "16",
          "Leão"
        ],
        [
          "7º",
          "7516",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "2056",
          "14",
          "Gato"
        ],
        [
          "9º",
          "9816",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "4451",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 21h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5088",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "1103",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "5361",
          "16",
          "Leão"
        ],
        [
          "4º",
          "1505",
          "02",
          "Águia"
        ],
        [
          "5º",
          "1402",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "4459",
          "",
          ""
        ],
        [
          "7º [mult]",
          "612",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 21h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5088",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "1103",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "5361",
          "16",
          "Leão"
        ],
        [
          "4º",
          "1505",
          "02",
          "Águia"
        ],
        [
          "5º",
          "1402",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "5151",
          "13",
          "Galo"
        ],
        [
          "7º",
          "0135",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "8060",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "8315",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "6120",
          "05",
          "Cachorro"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8474",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "9240",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "2765",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "6011",
          "03",
          "Burro"
        ],
        [
          "5º",
          "1358",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "8926",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "4270",
          "18",
          "Porco"
        ],
        [
          "8º",
          "7461",
          "16",
          "Leão"
        ],
        [
          "9º",
          "4051",
          "13",
          "Galo"
        ],
        [
          "10º",
          "2556",
          "14",
          "Gato"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2968",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "1968",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "9278",
          "20",
          "Peru"
        ],
        [
          "4º",
          "5798",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "0504",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "2195",
          "24",
          "Veado"
        ],
        [
          "7º",
          "9927",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "6679",
          "20",
          "Peru"
        ],
        [
          "9º",
          "8888",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "8205",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7065",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "3419",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "2484",
          "21",
          "Touro"
        ],
        [
          "4º",
          "7673",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "3832",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "7327",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "0446",
          "12",
          "Elefante"
        ],
        [
          "8º",
          "6187",
          "22",
          "Tigre"
        ],
        [
          "9º",
          "5943",
          "11",
          "Cavalo"
        ],
        [
          "10º",
          "4376",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 15:45h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5946",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "4780",
          "20",
          "Peru"
        ],
        [
          "3º",
          "4112",
          "03",
          "Burro"
        ],
        [
          "4º",
          "2341",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "7785",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "5442",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "9713",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "4814",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "6021",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "0954",
          "14",
          "Gato"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 18h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7136",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "2762",
          "16",
          "Leão"
        ],
        [
          "3º",
          "5659",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "1154",
          "14",
          "Gato"
        ],
        [
          "5º",
          "7294",
          "24",
          "Veado"
        ],
        [
          "6º",
          "7251",
          "13",
          "Galo"
        ],
        [
          "7º",
          "1761",
          "16",
          "Leão"
        ],
        [
          "8º",
          "3655",
          "14",
          "Gato"
        ],
        [
          "9º",
          "6294",
          "24",
          "Veado"
        ],
        [
          "10º",
          "2966",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 20:00",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0311",
          "03",
          "Burro"
        ],
        [
          "2º",
          "4498",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "9063",
          "16",
          "Leão"
        ],
        [
          "4º",
          "4764",
          "16",
          "Leão"
        ],
        [
          "5º",
          "0341",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "0494",
          "24",
          "Veado"
        ],
        [
          "7º",
          "3407",
          "02",
          "Águia"
        ],
        [
          "8º",
          "1966",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "1834",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "6678",
          "20",
          "Peru"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7947",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "9874",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "3993",
          "24",
          "Veado"
        ],
        [
          "4º",
          "0720",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "0027",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "2561",
          "",
          ""
        ],
        [
          "7º [mult]",
          "468",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7947",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "9874",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "3993",
          "24",
          "Veado"
        ],
        [
          "4º",
          "0720",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "0027",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "7930",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "9897",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "4792",
          "23",
          "Urso"
        ],
        [
          "9º",
          "7430",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "2610",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4285",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "5384",
          "21",
          "Touro"
        ],
        [
          "3º",
          "0572",
          "18",
          "Porco"
        ],
        [
          "4º",
          "5357",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "6820",
          "05",
          "Cachorro"
        ],
        [
          "6º [soma]",
          "2418",
          "",
          ""
        ],
        [
          "7º [mult]",
          "070",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4285",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "5384",
          "21",
          "Touro"
        ],
        [
          "3º",
          "0572",
          "18",
          "Porco"
        ],
        [
          "4º",
          "5357",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "6820",
          "05",
          "Cachorro"
        ],
        [
          "6º",
          "4505",
          "02",
          "Águia"
        ],
        [
          "7º",
          "2353",
          "14",
          "Gato"
        ],
        [
          "8º",
          "8875",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "5427",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "3578",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1617",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "9085",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "3515",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "5027",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "2336",
          "09",
          "Cobra"
        ],
        [
          "6º [soma]",
          "1580",
          "",
          ""
        ],
        [
          "7º [mult]",
          "690",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1617",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "9085",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "3515",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "5027",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "2336",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "1935",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "6050",
          "13",
          "Galo"
        ],
        [
          "8º",
          "1812",
          "03",
          "Burro"
        ],
        [
          "9º",
          "7557",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "8934",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6597",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "3574",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "0864",
          "16",
          "Leão"
        ],
        [
          "4º",
          "3093",
          "24",
          "Veado"
        ],
        [
          "5º",
          "0043",
          "11",
          "Cavalo"
        ],
        [
          "6º [soma]",
          "4171",
          "",
          ""
        ],
        [
          "7º [mult]",
          "577",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6597",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "3574",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "0864",
          "16",
          "Leão"
        ],
        [
          "4º",
          "3093",
          "24",
          "Veado"
        ],
        [
          "5º",
          "0043",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "6303",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "5580",
          "20",
          "Peru"
        ],
        [
          "8º",
          "9769",
          "18",
          "Porco"
        ],
        [
          "9º",
          "7443",
          "11",
          "Cavalo"
        ],
        [
          "10º",
          "3266",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4165",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "1108",
          "02",
          "Águia"
        ],
        [
          "3º",
          "3422",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "2483",
          "21",
          "Touro"
        ],
        [
          "5º",
          "2503",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "3681",
          "",
          ""
        ],
        [
          "7º [mult]",
          "614",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4165",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "1108",
          "02",
          "Águia"
        ],
        [
          "3º",
          "3422",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "2483",
          "21",
          "Touro"
        ],
        [
          "5º",
          "2503",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "4132",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "1144",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "6028",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "5823",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "0808",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5479",
          "20",
          "Peru"
        ],
        [
          "2º",
          "0955",
          "14",
          "Gato"
        ],
        [
          "3º",
          "6770",
          "18",
          "Porco"
        ],
        [
          "4º",
          "5054",
          "14",
          "Gato"
        ],
        [
          "5º",
          "6643",
          "11",
          "Cavalo"
        ],
        [
          "6º [soma]",
          "4901",
          "",
          ""
        ],
        [
          "7º [mult]",
          "232",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5479",
          "20",
          "Peru"
        ],
        [
          "2º",
          "0955",
          "14",
          "Gato"
        ],
        [
          "3º",
          "6770",
          "18",
          "Porco"
        ],
        [
          "4º",
          "5054",
          "14",
          "Gato"
        ],
        [
          "5º",
          "6643",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "5065",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "4970",
          "18",
          "Porco"
        ],
        [
          "8º",
          "7575",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "9504",
          "01",
          "Avestruz"
        ],
        [
          "10º",
          "2015",
          "04",
          "Borboleta"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5345",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "4930",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "2854",
          "14",
          "Gato"
        ],
        [
          "4º",
          "7798",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "5492",
          "23",
          "Urso"
        ],
        [
          "6º [soma]",
          "6419",
          "",
          ""
        ],
        [
          "7º [mult]",
          "350",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5345",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "4930",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "2854",
          "14",
          "Gato"
        ],
        [
          "4º",
          "7798",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "5492",
          "23",
          "Urso"
        ],
        [
          "6º",
          "5427",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "3987",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "4359",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "5048",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "5240",
          "10",
          "Coelho"
        ]
      ]
    }
  ],
  "NACIONAL": [
    {
      "titulo": "Nacional - LN 02:00 - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8360",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "7176",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "3129",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "4747",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "1019",
          "05",
          "Cachorro"
        ],
        [
          "6º [soma]",
          "4431",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 08:00 - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3430",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "5413",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "7873",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "6225",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "5349",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "8290",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 10:00 - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3123",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "6975",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "3898",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "9029",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "7983",
          "21",
          "Touro"
        ],
        [
          "6º [soma]",
          "1008",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 12:00 - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5236",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "3353",
          "14",
          "Gato"
        ],
        [
          "3º",
          "9627",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "9789",
          "23",
          "Urso"
        ],
        [
          "5º",
          "4792",
          "23",
          "Urso"
        ],
        [
          "6º [soma]",
          "2797",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 15:00 - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4477",
          "20",
          "Peru"
        ],
        [
          "2º",
          "8943",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "8508",
          "02",
          "Águia"
        ],
        [
          "4º",
          "3278",
          "20",
          "Peru"
        ],
        [
          "5º",
          "5620",
          "05",
          "Cachorro"
        ],
        [
          "6º [soma]",
          "0826",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 17:00 - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6603",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "9788",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "9323",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "8803",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "6339",
          "10",
          "Coelho"
        ],
        [
          "6º [soma]",
          "0856",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Nacional - LN 20:00 - Resultado do dia 08/10/2024 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5655",
          "14",
          "Gato"
        ],
        [
          "2º",
          "8575",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "0732",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "5005",
          "02",
          "Águia"
        ],
        [
          "5º",
          "7365",
          "17",
          "Macaco"
        ],
        [
          "6º [soma]",
          "7332",
          "",
          ""
        ]
      ]
    }
  ]
};