const bam = {
  "MALUCA - Bahia": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Pr?mio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1?",
          "6084",
          "21",
          "Touro"
        ],
        [
          "2?",
          "5462",
          "16",
          "Le?o"
        ],
        [
          "3?",
          "5271",
          "18",
          "Porco"
        ],
        [
          "4?",
          "7249",
          "13",
          "Galo"
        ],
        [
          "5?",
          "1990",
          "23",
          "Urso"
        ],
        [
          "6?",
          "1101",
          "01",
          "Avestruz"
        ],
        [
          "7?",
          "8465",
          "17",
          "Macaco"
        ],
        [
          "8?",
          "4875",
          "19",
          "Pav?o"
        ],
        [
          "9?",
          "9760",
          "15",
          "Jacar?"
        ],
        [
          "10?",
          "0481",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Pr?mio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1?",
          "5091",
          "23",
          "Urso"
        ],
        [
          "2?",
          "9454",
          "14",
          "Gato"
        ],
        [
          "3?",
          "3980",
          "20",
          "Peru"
        ],
        [
          "4?",
          "5351",
          "13",
          "Galo"
        ],
        [
          "5?",
          "1934",
          "09",
          "Cobra"
        ],
        [
          "6?",
          "8866",
          "17",
          "Macaco"
        ],
        [
          "7?",
          "9600",
          "25",
          "Vaca"
        ],
        [
          "8?",
          "2297",
          "25",
          "Vaca"
        ],
        [
          "9?",
          "2830",
          "08",
          "Camelo"
        ],
        [
          "10?",
          "2275",
          "19",
          "Pav?o"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Pr?mio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1?",
          "0988",
          "22",
          "Tigre"
        ],
        [
          "2?",
          "3695",
          "24",
          "Veado"
        ],
        [
          "3?",
          "6848",
          "12",
          "Elefante"
        ],
        [
          "4?",
          "0511",
          "03",
          "Burro"
        ],
        [
          "5?",
          "5244",
          "11",
          "Cavalo"
        ],
        [
          "6?",
          "5252",
          "13",
          "Galo"
        ],
        [
          "7?",
          "9521",
          "06",
          "Cabra"
        ],
        [
          "8?",
          "2387",
          "22",
          "Tigre"
        ],
        [
          "9?",
          "4484",
          "21",
          "Touro"
        ],
        [
          "10?",
          "9705",
          "02",
          "?guia"
        ]
      ]
    },
    {
      "titulo": "19h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Pr?mio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1?",
          "1254",
          "14",
          "Gato"
        ],
        [
          "2?",
          "3473",
          "19",
          "Pav?o"
        ],
        [
          "3?",
          "9137",
          "10",
          "Coelho"
        ],
        [
          "4?",
          "9669",
          "18",
          "Porco"
        ],
        [
          "5?",
          "8401",
          "01",
          "Avestruz"
        ],
        [
          "6?",
          "0036",
          "09",
          "Cobra"
        ],
        [
          "7?",
          "9549",
          "13",
          "Galo"
        ],
        [
          "8?",
          "2917",
          "05",
          "Cachorro"
        ],
        [
          "9?",
          "5222",
          "06",
          "Cabra"
        ],
        [
          "10?",
          "0937",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "21h - MALUCA - BA - Resultado do dia 07/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Pr?mio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1?",
          "1387",
          "22",
          "Tigre"
        ],
        [
          "2?",
          "2884",
          "21",
          "Touro"
        ],
        [
          "3?",
          "3858",
          "15",
          "Jacar?"
        ],
        [
          "4?",
          "1145",
          "12",
          "Elefante"
        ],
        [
          "5?",
          "3188",
          "22",
          "Tigre"
        ],
        [
          "6?",
          "2793",
          "24",
          "Veado"
        ],
        [
          "7?",
          "3191",
          "23",
          "Urso"
        ],
        [
          "8?",
          "2794",
          "24",
          "Veado"
        ],
        [
          "9?",
          "2665",
          "17",
          "Macaco"
        ],
        [
          "10?",
          "5943",
          "11",
          "Cavalo"
        ]
      ]
    }
  ]
};